Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

    OrdererEndpoints:
      - "orderer.GOnetwork.com:7050"
      - "orderer2.GOnetwork.com:8050"
      - "orderer3.GOnetwork.com:9050"
      - "orderer4.GOnetwork.com:10050"

  - &buyer
    Name: buyerMSP
    ID: buyerMSP

    MSPDir: ../../setup1/buyer-vm1/crypto-config/peerOrganizations/buyer.GOnetwork.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('buyerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('buyerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('buyerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('buyerMSP.member')"

    AnchorPeers:
      - Host: b-peer0.buyer.GOnetwork.com
        Port: 7051

  - &eproducer
    Name: eproducerMSP

    ID: eproducerMSP

    MSPDir: ../../setup1/eproducer-vm2/crypto-config/peerOrganizations/eproducer.GOnetwork.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('eproducerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('eproducerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('eproducerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('eproducerMSP.member')"

    AnchorPeers:
      - Host: e-peer0.eproducer.GOnetwork.com
        Port: 9051

  - &issuer
    Name: issuerMSP

    ID: issuerMSP

    MSPDir: ../../setup1/issuer-vm3/crypto-config/peerOrganizations/issuer.GOnetwork.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('issuerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('issuerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('issuerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('issuerMSP.member')"

    AnchorPeers:
      - Host: i-peer0.issuer.GOnetwork.com
        Port: 11051

  - &hproducer
    Name: hproducerMSP

    ID: hproducerMSP

    MSPDir: ../../setup1/hproducer-vm5/crypto-config/peerOrganizations/hproducer.GOnetwork.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('hproducerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('hproducerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('hproducerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('hproducerMSP.member')"

    AnchorPeers:
      - Host: h-peer0.hproducer.GOnetwork.com
        Port: 13051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft

  EtcdRaft:
    Consenters:
      - Host: orderer.GOnetwork.com
        Port: 7050
        ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer.GOnetwork.com/tls/server.crt
        ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer.GOnetwork.com/tls/server.crt
      - Host: orderer2.GOnetwork.com
        Port: 8050
        ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer2.GOnetwork.com/tls/server.crt
        ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer2.GOnetwork.com/tls/server.crt
      - Host: orderer3.GOnetwork.com
        Port: 9050
        ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer3.GOnetwork.com/tls/server.crt
        ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer3.GOnetwork.com/tls/server.crt
      - Host: orderer4.GOnetwork.com
        Port: 10050
        ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer4.GOnetwork.com/tls/server.crt
        ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer4.GOnetwork.com/tls/server.crt
  Addresses:
    - orderer.GOnetwork.com:7050
    - orderer2.GOnetwork.com:8050
    - orderer3.GOnetwork.com:9050
    - orderer4.GOnetwork.com:10050

  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ChannelUsingRaft:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.GOnetwork.com
            Port: 7050
            ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer.GOnetwork.com/tls/server.crt
            ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer.GOnetwork.com/tls/server.crt
          - Host: orderer2.GOnetwork.com
            Port: 8050
            ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer2.GOnetwork.com/tls/server.crt
            ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer2.GOnetwork.com/tls/server.crt
          - Host: orderer3.GOnetwork.com
            Port: 9050
            ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer3.GOnetwork.com/tls/server.crt
            ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer3.GOnetwork.com/tls/server.crt
          - Host: orderer4.GOnetwork.com
            Port: 10050
            ClientTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer4.GOnetwork.com/tls/server.crt
            ServerTLSCert: ../../setup1/orderer-vm4/crypto-config/ordererOrganizations/GOnetwork.com/orderers/orderer4.GOnetwork.com/tls/server.crt
      Organizations:
        - <<: *OrdererOrg
      Capabilities:
        - <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *buyer
        - *eproducer
        - *issuer
        - *hproducer
      Capabilities: *ApplicationCapabilities