test:
  workers:
    type: local
    number: 5
  rounds:
    - label: TransfereGO
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 40
      workload:
        module: benchmarks/scenario/GOconversion/transfereGO.js
    # - label: Query a car.
    #   rateControl:
    #     - type: fixed-load
    #       opts:
    #         transactionLoad: 5
    #   workload:
    #     module: benchmarks/samples/fabric/pavan-v2.2/queryCar.js
    #     arguments:
    #       assets: 1000
    - label: Query a specific eGO
      description: Query a specific eGO.
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 220
      workload:
        module: benchmarks/scenario/GOconversion/queryeGO.js
    # - label: Query_Car_1
    #   txDuration:
    #   - 30
    #   rateControl:
    #   - type: fixed-load
    #     opts:
    #       transactionLoad: 5
    #   workload:
    #     module: benchmarks/samples/fabric/pavan-v2.2/queryCar.js
    #     arguments:
    #       assets: 1000
    # - label: Create_Car_1
    #   txDuration:
    #   - 30
    #   rateControl:
    #     - type: fixed-load
    #       opts:
    #         transactionLoad: 5
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
