test:
  workers:
    type: local
    number: 5
  rounds:
    - label: Read Public eGOs
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 40
      workload:
        module: benchmarks/scenario/GOconversion/ReadPubliceGO.js
  #  - label: Query a specific public eGO
  #    description: Query a specific public eGO.
  #    txNumber: 1000
  #    rateControl:
  #      type: fixed-rate
  #      opts:
  #        tps: 220
  #    workload:
  #      module: benchmarks/scenario/GOconversion/ReadPubliceGO.js
    # - label: Query_Car_1
    #   txDuration:
    #   - 30
    #   rateControl:
    #   - type: fixed-load
    #     opts:
    #       transactionLoad: 5
    #   workload:
    #     module: benchmarks/samples/fabric/pavan-v2.2/queryCar.js
    #     arguments:
    #       assets: 1000
    # - label: Create_Car_1
    #   txDuration:
    #   - 30
    #   rateControl:
    #     - type: fixed-load
    #       opts:
    #         transactionLoad: 5
    #   workload:
    #     module: benchmarks/scenario/simple/pavan-v2.2/createCar.js
