version: "3.8"

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.5.0
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/pavan-v2.2/config.yaml
      - CALIPER_NETWORKCONFIG=networks/fabric/pavan-v2.1/network-config_2.2.yaml
    volumes:
      - ./../../../caliper/caliper-benchmarks/:/hyperledger/caliper/workspace
      - ./../crypto-config/:/hyperledger/caliper/workspace/crypto-config
    network_mode: host
