version: "3.8"

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.6.0
    command: launch manager --caliper-fabric-gateway-enabled
    environment:
      - CALIPER_BIND_SUT=fabric:2.1.0
      - CALIPER_BENCHCONFIG=caliper-config-GO/bench-config.yaml
      - CALIPER_NETWORKCONFIG=network-config.yaml
    volumes:
      - ./../../../caliper/caliper-benchmarks/:/hyperledger/caliper/workspace
      - ./../crypto-config/:/hyperledger/caliper/workspace/crypto-config
    network_mode: host
