name: Caliper Test
version: "2.0.0"

caliper:
  blockchain: fabric

info:
  Version: 2.2.0
  Size: 4 Orgs, 8 Peers, 4 clients, 4 orderers
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

channels:
  - channelName: mychannel
    contracts:
    - id: conversion

organizations:
  - mspid: buyerMSP
    identities:
      certificates:
        - name: 'buyer-client'
          clientPrivateKey:
            path: '../crypto-config/peerOrganizations/buyer.GOnetwork.com/b-users/Admin@buyer.GOnetwork.com/msp/keystore/*'
          clientSignedCert:
            path: '../crypto-config/peerOrganizations/buyer.GOnetwork.com/b-users/Admin@buyer.GOnetwork.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: './connection_profiles/ccp-buyer.json'    