name: Caliper Test
version: "2.0.0"

caliper:
  blockchain: fabric

info:
  Version: 2.2.0
  Size: 4 Orgs, 8 Peers, 4 clients, 4 orderers
  Orderer: Raft
  Distribution: Single Host
  StateDB: CouchDB

channels:
  - channelName: mychannel25
    contracts:
    - id: conversion

organizations:
  - mspid: buyerMSP
    identities:
      certificates:
        - name: 'buyer-client'
          clientPrivateKey:
            path: '/usr/local/go/src/github.com/JonaAlbrecht/caliper-workspace/crypto-config/peerOrganizations/buyer.GOnetwork.com/b-users/Admin@buyer.GOnetwork.com/msp/keystore/dfafb76bc66fadc433e1f0f52d399bdbb8eb6b00c50535ddcb439571ecd21db0_sk'
          clientSignedCert:
            path: './crypto-config/peerOrganizations/buyer.GOnetwork.com/b-users/Admin@buyer.GOnetwork.com/msp/signcerts/cert.pem'
    connectionProfile:
      path: './networks/connection_profiles/ccp-buyer.yaml'    