version: "3.8"

networks:
  test:

services:
  ca_hproducer:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.hproducer.GOnetwork.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/hproducer:/etc/hyperledger/fabric-ca-server
    container_name: ca.hproducer.GOnetwork.com
    hostname: ca.hproducer.GOnetwork.com
    networks:
      - test
