version: "2.4"

#this brings up the root certificate authority hosted by the issuing body
#it uses the hyperledger fabric-ca docker image and the fabric-samples binary/executable fabric-ca-server
#this project decided to employ a single root certificate authority because identity provision and issuance as well as the initial
#audit of production devices will remain with the issuing body

networks:
  test:

services:
  ca_issuer:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.issuer.GOnetwork.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/issuer:/etc/hyperledger/fabric-ca-server
    container_name: ca.issuer.GOnetwork.com
    hostname: ca.issuer.GOnetwork.com
    networks:
      - test
